In [12]:
import sys, pandas as pd
sys.path.append("../utils/")

from utilities import get_data_frame,region_selection_by_country

df = pd.DataFrame()
frame = get_data_frame()

def get_frame_by_wine_name(frame, name):
    df = pd.DataFrame(frame)
    df = df[df['Name'] == name]
    return df

def region_selection_by_country(frame, country):
    df = pd.DataFrame(frame)
    df = df[df['Country'] == country]
    return df

def wine_style_selection_by_country_and_region(frame, country, region):
    df = pd.DataFrame(frame)
    df = df[df['Country'] == country]
    df = df[df['Region'].str.contains(region, na=False)]
    return df

def df_selection_by_country_and_region_and_wine_style(frame, country, region, wine_style):
    df = pd.DataFrame(frame)
    df = df[df['Country'] == country]
    df = df[df['Region'].str.contains(region, na=False)]
    df = df[df['Wine style'] == wine_style]
    return df

df = region_selection_by_country(frame, "Australia")
wines = df['Name'].unique()
# df = wine_style_selection_by_country_and_region(frame, "Australia", "Fleurieu")
df = df_selection_by_country_and_region_and_wine_style(frame, "Australia", "Fleurieu", "Australian Shiraz")

df = get_frame_by_wine_name(frame, "Fields Of Joy Shiraz 2014")
df

,Unnamed: 0,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Grapes,Food pairings,Bold,Tannin,Sweet,Acidic,Country
0,0,Fields Of Joy Shiraz 2014,4.0,203,28.99,Australia / South Australia / Mount Lofty Rang...,Two Hands,Australian Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.0,47.13,20.62,43.57,Australia