Import required libraries

In [11]:
import os, sys
import pandas as pd
import glob
import ast

Append uitilies folder to system python path  
What are the things inside Util package?
    The function that gets all csv files into one data frame

In [12]:
sys.path.append("../utils/")

The function that gets all csv files into one data frame from data_sources folder

In [13]:
def get_data_frame():
    path = r'..\data_sources'
    filenames = glob.glob(os.path.join(path + "/*.csv"))
    li = []

    for filename in filenames:
        df = pd.read_csv(filename, index_col=None, header=0)
        df['Country'] = filename.split('\\')[2].split('_')[0]
        li.append(df)

    
    frame = pd.concat(li, axis=0, ignore_index=True)

    return frame

df = get_data_frame()
df.head()

# we can also use this as `from utilities import get_data_frame`

,Unnamed: 0,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Grapes,Food pairings,Bold,Tannin,Sweet,Acidic,Country
0,0,Fields Of Joy Shiraz 2014,4.0,203,28.99,Australia / South Australia / Mount Lofty Rang...,Two Hands,Australian Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,47.13000,20.62,43.570,Australia
1,1,Shotfire GSM 2018,3.9,36,19.49,Australia / South Australia / Barossa,Thorn-Clarke,Australian Rhône Blend Red,14.500000,"Mourvedre, Shiraz/Syrah, Grenache","['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']",85.00,50.63000,9.05,43.000,Australia
2,2,Passion has Red Lips 2020,3.8,350,27.50,Australia / South Australia / Fleurieu / McLar...,Some Young Punks,Australian Cabernet - Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",85.00,49.37000,8.19,44.780,Australia
3,3,The Hermit Crab Viognier - Marsanne 2018,3.8,1026,16.99,Australia / South Australia / Fleurieu / McLar...,d'Arenberg,NaN,13.794543,NaN,[],61.73,46.29527,9.05,53.555,Australia
4,4,Cabernet Sauvignon (Batch No. 1 & 3) 2019,3.8,969,14.99,Australia / South Eastern Australia,Gentleman's Collection,Australian Cabernet Sauvignon,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",76.34,49.36000,16.02,47.890,Australia

Also Some other functions were already defined to reuse
   1. The function that gives country spesific dataframe by using given Data frame and Country name
   2. The function that gives country and region spesific dataframe by using given Data frame, Country name and
       region
   3. The function that gives country, region and wine style spesific dataframe by using given Data frame, Country    
       name, region and wine style
   4. The function that gives dataframe of wine by using given Data frame and wine name

1. The function that gives country spesific dataframe by using given Data frame and Country name

In [5]:
def filter_by_country(frame, country):
    df = pd.DataFrame(frame)
    df = df[df['Country'] == country]
    return df

aus_data_frame = filter_by_country(df, "Australia")
aus_data_frame.head()

,Unnamed: 0,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Grapes,Food pairings,Bold,Tannin,Sweet,Acidic,Country
0,0,Fields Of Joy Shiraz 2014,4.0,203,28.99,Australia / South Australia / Mount Lofty Rang...,Two Hands,Australian Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",85.00,47.13000,20.62,43.570,Australia
1,1,Shotfire GSM 2018,3.9,36,19.49,Australia / South Australia / Barossa,Thorn-Clarke,Australian Rhône Blend Red,14.500000,"Mourvedre, Shiraz/Syrah, Grenache","['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']",85.00,50.63000,9.05,43.000,Australia
2,2,Passion has Red Lips 2020,3.8,350,27.50,Australia / South Australia / Fleurieu / McLar...,Some Young Punks,Australian Cabernet - Shiraz,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",85.00,49.37000,8.19,44.780,Australia
3,3,The Hermit Crab Viognier - Marsanne 2018,3.8,1026,16.99,Australia / South Australia / Fleurieu / McLar...,d'Arenberg,NaN,13.794543,NaN,[],61.73,46.29527,9.05,53.555,Australia
4,4,Cabernet Sauvignon (Batch No. 1 & 3) 2019,3.8,969,14.99,Australia / South Eastern Australia,Gentleman's Collection,Australian Cabernet Sauvignon,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",76.34,49.36000,16.02,47.890,Australia

2. The function that gives country and region spesific dataframe by using given Data frame, Country name and
       region

In [7]:
def filter_by_country_and_region(frame, country, region):
    df = pd.DataFrame(frame)
    df = df[df['Country'] == country]
    df = df[df['Region'].str.contains(region, na=False)]
    return df

aus_barossa_data_frame = filter_by_country_and_region(df, "Australia", "Barossa")
aus_barossa_data_frame.head()

,Unnamed: 0,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Grapes,Food pairings,Bold,Tannin,Sweet,Acidic,Country
1,1,Shotfire GSM 2018,3.9,36,19.49,Australia / South Australia / Barossa,Thorn-Clarke,Australian Rhône Blend Red,14.500000,"Mourvedre, Shiraz/Syrah, Grenache","['Beef', 'Pasta', 'Lamb', 'Game (deer, venison)']",85.00,50.63000,9.05,43.000,Australia
8,8,Shotfire Quartage 2016,3.8,93,17.99,Australia / South Australia / Barossa,Thorn-Clarke,Australian Bordeaux Blend,14.500000,"Cabernet Franc, Malbec, Cabernet Sauvignon","['Beef', 'Pasta', 'Lamb', 'Game (deer, venison...",85.00,56.40000,10.85,65.280,Australia
9,9,Stonehorse Shiraz 2018,4.0,288,29.17,Australia / South Australia / Barossa / Baross...,Kaesler,Australian Shiraz,14.000000,100 Shiraz/Syrah,"['Beef', 'Lamb', 'Game (deer, venison)', 'Poul...",84.04,44.21000,22.10,41.950,Australia
13,13,Barossa Valley Cabernet Sauvignon 2018,3.8,91,21.33,Australia / South Australia / Barossa / Baross...,Schild Estate,Australian Cabernet Sauvignon,13.794543,NaN,"['Beef', 'Lamb', 'Poultry']",69.12,52.56000,7.54,52.700,Australia
18,18,Thorny Devil Grenache 2021,4.0,33,23.74,Australia / South Australia / Barossa / Baross...,Thistledown,NaN,13.794543,NaN,[],61.73,46.29527,9.05,53.555,Australia

3. The function that gives country, region and wine style spesific dataframe by using given Data frame, Country    
       name, region and wine style

In [10]:
def filter_by_country_and_region_and_wine_style(frame, country, region, wine_style):
    df = pd.DataFrame(frame)
    df = df[df['Country'] == country]
    df = df[df['Region'].str.contains(region, na=False)]
    df = df[df['Wine style'] == wine_style]
    return df

aus_barossa_shiraz_data_frame = filter_by_country_and_region_and_wine_style(df, "Australia", "Barossa","Australian Cabernet - Shiraz")
aus_barossa_shiraz_data_frame.head()

,Unnamed: 0,Name,Rating,Number of Ratings,Price,Region,Winery,Wine style,Alcohol content,Grapes,Food pairings,Bold,Tannin,Sweet,Acidic,Country
279,279,Narrow Road Vineyard Shiraz - Cabernet 2018,4.4,54,34.99,Australia / South Australia / Barossa / Baross...,Schild Estate,Australian Cabernet - Shiraz,14.5,"Shiraz/Syrah, Cabernet Sauvignon",[],61.73,46.29527,9.05,53.555,Australia

4. The function that gives dataframe of wine by using given Data frame and wine name

In [14]:
def get_frame_by_wine_name(frame, name):
    df = pd.DataFrame(frame)
    df = df[df['Name'] == name]
    return df

Fields_Of_Joy_Shiraz_data_frame = get_frame_by_wine_name(df, "Fields Of Joy Shiraz 2014")
Fields_Of_Joy_Shiraz_data_frame

wine_food_pairings = Fields_Of_Joy_Shiraz_data_frame["Food pairings"].iloc[0] if not df.empty else []
food_pairings_list = ast.literal_eval(wine_food_pairings)

print(food_pairings_list)
# for food in wine_food_pairings:
#     print(food)

['Beef', 'Lamb', 'Game (deer, venison)', 'Poultry']